export const navigationItems = [
  {
    id: 'dashboard',
    shortLabel: 'DB',
    href: '/',
    isEnabled: true,
    showInBottomNav: true,
  },
  {
    id: 'transactions',
    shortLabel: 'TX',
    href: '/transactions',
    isEnabled: true,
    showInBottomNav: true,
  },
  {
    id: 'categories',
    shortLabel: 'CT',
    href: '/categories',
    isEnabled: true,
    showInBottomNav: false,
  },
  {
    id: 'budgets',
    shortLabel: 'BG',
    href: '/budgets',
    isEnabled: true,
    showInBottomNav: false,
  },
  {
    id: 'analytics',
    shortLabel: 'AN',
    href: '/analytics',
    isEnabled: true,
    showInBottomNav: false,
  },
  {
    id: 'notifications',
    shortLabel: 'NT',
    href: '/notifications',
    isEnabled: true,
    showInBottomNav: true,
  },
  {
    id: 'settings',
    shortLabel: 'ST',
    href: '/settings',
    isEnabled: true,
    showInBottomNav: false,
  },
];
