import type { FinanceWorkspace } from '../finance.types';

export function createPreviewWorkspace(): FinanceWorkspace {
  return {
    categories: [
      { id: 'category-salary', name: 'Salary' },
      { id: 'category-housing', name: 'Housing' },
      { id: 'category-food', name: 'Food and dining' },
      { id: 'category-transport', name: 'Transport' },
    ],
    subcategories: [
      { id: 'subcategory-rent', categoryId: 'category-housing', name: 'Rent' },
      { id: 'subcategory-groceries', categoryId: 'category-food', name: 'Groceries' },
      { id: 'subcategory-restaurants', categoryId: 'category-food', name: 'Restaurants' },
      { id: 'subcategory-transit', categoryId: 'category-transport', name: 'Transit' },
    ],
    transactions: [
      {
        id: 'transaction-salary-jan',
        amount: 6500,
        type: 'income',
        categoryId: 'category-salary',
        subcategoryId: null,
        date: '2026-01-01',
        description: 'Monthly salary',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-rent-jan',
        amount: 2100,
        type: 'expense',
        categoryId: 'category-housing',
        subcategoryId: 'subcategory-rent',
        date: '2026-01-03',
        description: 'Apartment rent',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-grocery-jan',
        amount: 164.2,
        type: 'expense',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-groceries',
        date: '2026-01-05',
        description: 'Weekly grocery run',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-restaurants-jan',
        amount: 108.5,
        type: 'expense',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-restaurants',
        date: '2026-01-12',
        description: 'Dinner downtown',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-transit-jan',
        amount: 74,
        type: 'expense',
        categoryId: 'category-transport',
        subcategoryId: 'subcategory-transit',
        date: '2026-01-18',
        description: 'Transit pass',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-salary-feb',
        amount: 6500,
        type: 'income',
        categoryId: 'category-salary',
        subcategoryId: null,
        date: '2026-02-01',
        description: 'Monthly salary',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-rent-feb',
        amount: 2100,
        type: 'expense',
        categoryId: 'category-housing',
        subcategoryId: 'subcategory-rent',
        date: '2026-02-03',
        description: 'Apartment rent',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-grocery-feb',
        amount: 192.4,
        type: 'expense',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-groceries',
        date: '2026-02-06',
        description: 'Weekly grocery run',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-restaurants-feb',
        amount: 146.75,
        type: 'expense',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-restaurants',
        date: '2026-02-14',
        description: 'Weekend dinner',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-transit-feb',
        amount: 82,
        type: 'expense',
        categoryId: 'category-transport',
        subcategoryId: 'subcategory-transit',
        date: '2026-02-19',
        description: 'Transit pass',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-salary',
        amount: 6500,
        type: 'income',
        categoryId: 'category-salary',
        subcategoryId: null,
        date: '2026-03-01',
        description: 'Monthly salary',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-rent',
        amount: 2100,
        type: 'expense',
        categoryId: 'category-housing',
        subcategoryId: 'subcategory-rent',
        date: '2026-03-03',
        description: 'Apartment rent',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-grocery',
        amount: 180.75,
        type: 'expense',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-groceries',
        date: '2026-03-05',
        description: 'Weekly grocery run',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-restaurants',
        amount: 204.9,
        type: 'expense',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-restaurants',
        date: '2026-03-12',
        description: 'Client dinner',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
      {
        id: 'transaction-transit',
        amount: 68,
        type: 'expense',
        categoryId: 'category-transport',
        subcategoryId: 'subcategory-transit',
        date: '2026-03-19',
        description: 'Transit pass',
        installmentGroupId: null,
        installmentIndex: null,
        installmentCount: null,
      },
    ],
    setAsides: [],
    budgets: [
      {
        id: 'budget-housing',
        categoryId: 'category-housing',
        subcategoryId: null,
        amount: 2500,
      },
      {
        id: 'budget-food-groceries',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-groceries',
        amount: 450,
      },
      {
        id: 'budget-food-restaurants',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-restaurants',
        amount: 220,
      },
      {
        id: 'budget-transport',
        categoryId: 'category-transport',
        subcategoryId: null,
        amount: 260,
      },
    ],
    budgetOverrides: [
      {
        id: 'budget-override-restaurants-march',
        categoryId: 'category-food',
        subcategoryId: 'subcategory-restaurants',
        month: '2026-03',
        amount: 320,
      },
    ],
    monthReviews: [],
  };
}
